# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table "blog_comments" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"blog_id" BIGINT NOT NULL,"comment" VARCHAR NOT NULL);
create table "blog_posts" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"title" VARCHAR NOT NULL,"body" VARCHAR NOT NULL);
alter table "blog_comments" add constraint "BLOGPOST_FK" foreign key("blog_id") references "blog_posts"("id") on update NO ACTION on delete NO ACTION;

# --- !Downs

alter table "blog_comments" drop constraint "BLOGPOST_FK";
drop table "blog_comments";
drop table "blog_posts";

